### ISSUE TITLE
How to change the length of decoded song?

### ISSUE THREAD

**Issue by TerakoyaAcademia** [MatthewAwesome/AIComposer#2]
Hi there,
I have been trying to change the length of the music (mean sequence). I tried to change some parameters in interpolate function as shown below.
```
def interpolate(model, start_seq, end_seq, num_steps, max_length=40,
                assert_same_length=True, temperature=0.5,
                individual_duration=5.0):
```
When i changed the max_length parameter and individual_duration parameter, i got the following result. 
![visual2](https://user-images.githubusercontent.com/85092129/142142864-40f9e3b7-4910-4d3c-bbc8-642143b0d23f.PNG)

As you can see, the reconstructed music is still of length 33 second. And the final interpolated song has a playing sequence of 33 seconds and there is silence for 7 seconds and start playing again. Is there any other way to make max length of the constructed music dynamic so that there is no empty notes in between.

**Comment by Aashu-Adhikari** [comment]
This issue can be solved by changing num_steps parameter. This generated new sequences hence the length can be increased.

`trio_16bar_mean = interpolate(trio_models[trio_interp_model], start_trio, end_trio, num_steps=6, max_length=256, individual_duration=32, temperature=temperature)`

By changing num_steps to 6, the model creates 4 new mean sequences.
hope this helps

**Comment by TerakoyaAcademia** [comment]
@Aashu-Adhikari , This worked. Thank you for time :)
